spring.application.name=simplechat
spring.datasource.url=jdbc:postgresql://localhost:5432/simplechat
spring.datasource.username=simplechat
spring.datasource.password=simplechat
spring.jpa.hibernate.ddl-auto=validate
spring.session.jdbc.initialize-schema=always
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
ollama.baseUrl=http://localhost:11434
ollama.model=qwen2.5:1.5b
ollama.timeoutSeconds=3600
