spring.application.name=simplechat
spring.datasource.url=postgresql://localhost:5432/simplechat
spring.datasource.username=simplechat
spring.datasource.password=simplechat
spring.jpa.hibernate.ddl-auto=update
spring.session.jdbc.initialize-schema=always